OBS: latest: handle "version is None"
Fix the Osmocom_OBS_latest job, which currently fails on git
repositories where no tagged release can be found with:

    File "/obs/lib/debian.py", line 96, in transform_version
      if "osmo-epdg-" in version:
         ^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: argument of type 'NoneType' is not iterable

Fixes: 9b36d2a8 ("OBS: fix up-to-date check for strongswan-epdg")
Change-Id: I69cb884d499d1f6a8cae4b4585d31b5bc095fd6e