anisble: gsm-tester: uhubctl: add "-n 1d50:4002"
uhubctl -p 123456 -a 1 is rejecting because uhubctl detects two hubs.
Selecting only one hub.

Fixes the error message:
    Error: changing port state for multiple hubs at once is not supported.
    Use -l to limit operation to one hub!

Change-Id: I2e3c248e4eaef39f18ff38d1055db6d552fc4d20