scripts/manuals: use debian-trixie-build
Fix that the Osmocom-release-manuals job was still using
debian-bookworm-build instead of debian-trixie-build to build the
manuals. We use the latter for building manuals in master-builds and
gerrit-verifications.

Without this patch building pyosmocom manuals failed with the following,
as python3-typing-extensions in debian bookworm is at version 4.4.0 but
typing_extensions >= 4.6.0 is needed for TypeAliasType. Trixie has
version 4.13.2.

AttributeError: module 'typing_extensions' has no attribute 'TypeAliasType'. Did you mean: 'TypeAlias'?

Fixes: OS#6916
Change-Id: I6ac302c8ea5836c5096f0d8ab36260cc6f7c11d9