OBS: fix using --conflict-pkgname
Use --conflict-pkgname as package name, instead of hardcoding
osmocom-$FEED.

Fix for:
  FileNotFoundError: [Errno 2] No such file or directory: '/obs/_cache/osmocom-nightly-asan'

Change-Id: I4ddb2e9adc25e7e8e8c9d17236b76d9f2e9c2a9c